#ifndef _LCOM_VBE_H_
#define _LCOM_VBE_H_

/* MEMORY MODELS */
#define VBE_INDEXED_MODE 4
#define VBE_DIRECT_MODE 6

/* FUNCTION CALLS */
// AH
#define VBE_FUNCTION_CALL 0x4F

// AL
#define VBE_SET_MODE 0x02
#define VBE_GET_MODE_INFO 0x01
#define VBE_GET_CONTROLLER_INFO 0x00

/* FUNCTION RETURN CODES */
// AH
#define VBE_SUCCESS 0x00
#define VBE_FAIL 0x01
#define VBE_UNSUPPORTED_FUNCTION 0x02
#define VBE_INVALID_FUNCTION 0x03

// AL
#define VBE_SUPPORTED_FUNCTION 0x4F

#endif // _LCOM_VBE_H_
